### PR TITLE
fix(sindi): fix compilation issues of sindi in versions prior to C++17

### LINKED ISSUE #1081: compile error in gcc 9.3.0
**Describe the bug**
complie in gcc 9.3.0 will report error.
Image
[[likely]] only support in c++20, complie with old gcc version will report error
**To Reproduce**
compile with gcc9.3.0

**Environment**
- vsag version: 0.16.1
- compiler version: gcc 9.3.0

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by inabao**
close #1081
## Summary by Sourcery

Fix compilation issues in sparse_term_datacell by conditionally falling back to __builtin_expect for branch prediction and restructuring heap operations for standards prior to C++20

Bug Fixes:
- Add preprocessor guard to use __builtin_expect when [[likely]] is unsupported
- Adjust heap operation placement to resolve compilation errors on older C++ standards

Enhancements:
- Remove redundant heap size check under KNN search

### CODE REVIEW

**Review by LHT129 — APPROVED** [review]
LGTM
